=== danydunk/Augusto/files/xml_schemas/GUI_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GUI">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="window">
						<xs:complexType>
								<xs:sequence>
								<xs:element name="pos" type="xs:string" />
								<xs:element name="class" type="xs:string" />							
								<xs:element name="title" type="xs:string" />
								<xs:element name="modal" type="xs:boolean" />
								<xs:element name="root" type="xs:boolean" />							
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="action_widget">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="pos" type="xs:string" />
												<xs:element name="class" type="xs:string" />
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="label" type="xs:string" />
												</xs:sequence>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="descriptor" type="xs:string" />
												</xs:sequence>
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="input_widget">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="pos" type="xs:string" />
												<xs:element name="class" type="xs:string" />
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="label" type="xs:string" />
												</xs:sequence>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="descriptor" type="xs:string" />
												</xs:sequence>
												<xs:element name="value" type="xs:string" />
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="selectable_widget">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="pos" type="xs:string" />
												<xs:element name="class" type="xs:string" />
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="label" type="xs:string" />
												</xs:sequence>
												<xs:sequence minOccurs="0" maxOccurs="1">
													<xs:element name="descriptor" type="xs:string" />
												</xs:sequence>
												<xs:element name="size" type="xs:int" />
												<xs:element name="selected" type="xs:int" />
										</xs:sequence>
											<xs:attribute name="id" type="xs:string" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:sequence>
							<xs:attribute name="id" type="xs:string" />
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="edge">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="from" type="xs:string" />
								<xs:sequence minOccurs="1" maxOccurs="unbounded">
									<xs:element name="to" type="xs:string" />
								</xs:sequence>
							</xs:sequence>
							<xs:attribute name="id" type="xs:string" />
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danydunk/Augusto/daniele/GUISemantics_RFT/files/for_test/xml/upm-small.xml
<?xml version="1.0" encoding="UTF-8"?><GUI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GUI_schema.xsd">
    <window id="w1">
        <title>Add Account</title>
        <modal>true</modal>
        <root>false</root>
        <input_widget id="w2007498480">
            <label>account</label>
            <text/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <input_widget id="w2007517576">
            <label>user id</label>
            <text/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <input_widget id="w2774944816">
            <label>password</label>
            <text/>
            <class>javax.swing.JPasswordField</class>
        </input_widget>
        <action_widget id="w2570453882">
            <label>generate</label>
            <class>javax.swing.JButton</class>
        </action_widget>
        <input_widget id="w2937018836">
            <label>url</label>
            <text/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <input_widget id="w2534235680">
            <label>notes</label>
            <text/>
            <class>javax.swing.JTextArea</class>
        </input_widget>
        <action_widget id="w3660345700">
            <label>ok</label>
            <class>javax.swing.JButton</class>
        </action_widget>
        <action_widget id="w3114841242">
            <label>cancel</label>
            <class>javax.swing.JButton</class>
        </action_widget>
    </window>
    <window id="w2">
        <title>/Users/daniele/Documents/work/InteractiveTesting/jfc-guitar-v1.1.1/upm-small-ripping/db - Universal Password Manager</title>
        <modal>false</modal>
        <root>true</root>
        <input_widget id="w2143515822">
            <label>search.gif</label>
            <text/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <selectable_widget id="w1030010946">
            <label>search.gif</label>
            <size>0</size>
            <class>javax.swing.JList</class>
        </selectable_widget>
        <action_widget id="w1593185608">
            <label>account</label>
            <class>javax.swing.JMenu</class>
        </action_widget>
        <action_widget id="w1005214592">
            <label>add account</label>
            <class>javax.swing.JMenuItem</class>
        </action_widget>
    </window>
    <edge id="w1005214592-w1">
        <from>w1005214592</from>
        <to>w1</to>
    </edge>
    <edge id="w3660345700-w2">
        <from>w3660345700</from>
        <to>w2</to>
    </edge>
    <edge id="w3114841242-w2">
        <from>w3114841242</from>
        <to>w2</to>
    </edge>
</GUI>

=== danydunk/Augusto/daniele/GUISemantics_RFT/resources/for_test/xml/GUI.xml
<?xml version="1.0" encoding="UTF-8"?>
<GUI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="GUI_schema.xsd">
	<window id="w1">
		<title>Init</title>
		<modal>false</modal>
		<root>true</root>
		<action_widget id="aw1">
			<label>add</label>
			<class></class>
		</action_widget>
		<action_widget id="aw2">
			<label>test</label>
			<class></class>
		</action_widget>
	</window>
	<window id="w2">
		<title>Form</title>
		<modal>false</modal>
		<root>false</root>
		<label></label>
		<action_widget id="aw3">
			<label>save</label>
			<class></class>
		</action_widget>
		<action_widget id="aw4">
			<label>back</label>
			<class></class>
		</action_widget>
		<input_widget id="iw1">
			<label>field1</label>
			<text></text>
			<class></class>
		</input_widget>
		<input_widget id="iw2">
			<label>field2</label>
			<text></text>
			<class></class>
		</input_widget>
	</window>
	<window id="w3">
		<title>Other</title>
		<modal>false</modal>
		<root>false</root>
		<label></label>
		<action_widget id="aw5">
			<label>add</label>
			<class></class>
		</action_widget>
		<input_widget id="iw3">
			<label>field3</label>
			<text></text>
			<class></class>
		</input_widget>
	</window>
	<edge id="e1">
		<from>aw1</from>
		<to>w2</to>
	</edge>
	<edge id="e2">
		<from>aw2</from>
		<to>w3</to>
	</edge>
</GUI>

=== danydunk/Augusto/files/for_test/xml/GUI.xml
<?xml version="1.0" encoding="UTF-8"?>
<GUI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="GUI_schema.xsd">
	<window id="w1">
		<pos>1:1</pos>
		<class>class</class>	
		<title>Init</title>
		<modal>false</modal>
		<root>true</root>
		<action_widget id="aw1">
			<pos>1:1</pos>
			<class>class</class>			
			<label>add</label>
		</action_widget>
		<action_widget id="aw2">
			<pos>1:1</pos>
			<class>class</class>			
			<label>test</label>
		</action_widget>
	</window>
	<window id="w2">
		<pos>1:1</pos>
		<class>class</class>
		<title>Form</title>
		<modal>false</modal>
		<root>false</root>
		<label></label>
		<action_widget id="aw3">
			<pos>1:1</pos>
			<class>class</class>			
			<label>save</label>
		</action_widget>
		<action_widget id="aw4">
			<pos>1:1</pos>
			<class>class</class>			
			<label>back</label>
		</action_widget>
		<input_widget id="iw1">
			<pos>1:1</pos>
			<class>class</class>			
			<label>field1</label>
			<value></value>
			<class></class>
		</input_widget>
		<input_widget id="iw2">
			<pos>1:1</pos>
			<class>class</class>			
			<label>field2</label>
			<value></value>
		</input_widget>
	</window>
	<window id="w3">
		<pos>1:1</pos>
		<class>class</class>
		<title>Other</title>
		<modal>false</modal>
		<root>false</root>
		<label></label>
		<action_widget id="aw5">
			<pos>1:1</pos>
			<class>class</class>			
			<label>add</label>
		</action_widget>
		<input_widget id="iw3">
			<pos>1:1</pos>
			<class>class</class>			
			<label>field3</label>
			<value></value>
		</input_widget>
	</window>
	<edge type="static" id="e1">
		<from>aw1</from>
		<to>w2</to>
	</edge>
	<edge type="static" id="e2">
		<from>aw2</from>
		<to>w3</to>
	</edge>
</GUI>

=== danydunk/Augusto/files/for_test/xml/upm-small.xml
<?xml version="1.0" encoding="UTF-8"?><GUI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GUI_schema.xsd">
    <window id="w1">
    	<pos>1:1</pos>
    	<class>class</class>
        <title>Add Account</title>
        <modal>true</modal>
        <root>false</root>
        <input_widget id="w2007498480">
        	<pos>1:1</pos>
            <label>account</label>
            <value/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <input_widget id="w2007517576">
        	<pos>1:1</pos>
            <label>user id</label>
            <value/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <input_widget id="w2774944816">
        	<pos>1:1</pos>
            <label>password</label>
            <value/>
            <class>javax.swing.JPasswordField</class>
        </input_widget>
        <action_widget id="w2570453882">
        	<pos>1:1</pos>
            <label>generate</label>
            <class>javax.swing.JButton</class>
        </action_widget>
        <input_widget id="w2937018836">
        	<pos>1:1</pos>
            <label>url</label>
            <value/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <input_widget id="w2534235680">
        	<pos>1:1</pos>
            <label>notes</label>
            <value/>
            <class>javax.swing.JTextArea</class>
        </input_widget>
        <action_widget id="w3660345700">
        	<pos>1:1</pos>
            <label>ok</label>
            <class>javax.swing.JButton</class>
        </action_widget>
        <action_widget id="w3114841242">
        	<pos>1:1</pos>
            <label>cancel</label>
            <class>javax.swing.JButton</class>
        </action_widget>
    </window>
    <window id="w2">
    	<pos>1:1</pos>
    	<class>class</class>
        <title>/Users/daniele/Documents/work/InteractiveTesting/jfc-guitar-v1.1.1/upm-small-ripping/db - Universal Password Manager</title>
        <modal>false</modal>
        <root>true</root>
        <input_widget id="w2143515822">
        	<pos>1:1</pos>
            <label>search.gif</label>
            <value/>
            <class>javax.swing.JTextField</class>
        </input_widget>
        <selectable_widget id="w1030010946">
        	<pos>1:1</pos>
            <label>search.gif</label>
            <size>0</size>
            <selected>-1</selected>
            <class>javax.swing.JList</class>
        </selectable_widget>
        <action_widget id="w1593185608">
        	<pos>1:1</pos>
            <label>account</label>
            <class>javax.swing.JMenu</class>
        </action_widget>
        <action_widget id="w1005214592">
        	<pos>1:1</pos>
            <label>add account</label>
            <class>javax.swing.JMenuItem</class>
        </action_widget>
    </window>
    <edge type="static" id="w1005214592-w1">
        <from>w1005214592</from>
        <to>w1</to>
    </edge>
    <edge type="static" id="w3660345700-w2">
        <from>w3660345700</from>
        <to>w2</to>
    </edge>
    <edge type="static" id="w3114841242-w2">
        <from>w3114841242</from>
        <to>w2</to>
    </edge>
</GUI>
