=== danydunk/Augusto/files/xml_schemas/Pattern_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pattern">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="window">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="title" type="xs:string" />
								<xs:element name="modal" type="xs:string" />
								<xs:element name="root" type="xs:string" />
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="action_widget">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="label" type="xs:string" />
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" />
											<xs:attribute name="card" type="xs:string" />
											<xs:attribute name="alloy" type="xs:string" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="selectable_widget">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="label" type="xs:string" />
												<xs:element name="size" type="xs:string" />
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" />
											<xs:attribute name="card" type="xs:string" />
											<xs:attribute name="alloy" type="xs:string" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="input_widget">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="label" type="xs:string" />
												<xs:element name="value" type="xs:string" />
											</xs:sequence>
											<xs:attribute name="id" type="xs:string" />
											<xs:attribute name="card" type="xs:string" />
											<xs:attribute name="alloy" type="xs:string" />
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:sequence>
							<xs:attribute name="id" type="xs:string" />
							<xs:attribute name="card" type="xs:string" />
							<xs:attribute name="alloy" type="xs:string" />
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence minOccurs="0" maxOccurs="unbounded">
					<xs:element name="edge">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="from" type="xs:string" />
								<xs:sequence minOccurs="1" maxOccurs="unbounded">
									<xs:element name="to" type="xs:string" />
								</xs:sequence>
							</xs:sequence>
							<xs:attribute name="id" type="xs:string" />
							<xs:attribute name="type" type="xs:string" />
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="id" type="xs:string" />
			<xs:attribute name="alloy" type="xs:string" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== danydunk/Augusto/daniele/GUISemantics_RFT/resources/xml/add_pattern_labelfree.xml
<?xml version="1.0" encoding="UTF-8"?>
<pattern xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../xml_schemas/Pattern_schema.xsd"
	alloy="ADD.als">
	<window id="initial" card="one" alloy="Initial">
		<title>.*</title>
		<modal>any</modal>
		<root>any</root>
		<action_widget id="aw1" card="one" alloy="Trigger">
			<label>.*</label>
		</action_widget>
		<selectable_widget id="sw1" card="one" alloy="List">
			<label>.*</label>
			<size>.*</size>
		</selectable_widget>
	</window>
	<window id="form_1" card="one" alloy="Form">
		<title>.*</title>
		<modal>any</modal>
		<root>any</root>
		<action_widget id="aw2" card="one" alloy="Ok">
			<label>.*</label>
		</action_widget>
		<action_widget id="aw3" card="one" alloy="Cancel">
			<label>.*</label>
		</action_widget>
		<input_widget id="iw1" card="some" alloy="Input">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="form_2" card="set" alloy="Form">
		<title>.*</title>
		<modal>any</modal>
		<root>any</root>
		<action_widget id="aw4" card="one" alloy="Ok">
			<label>.*</label>
		</action_widget>
		<action_widget id="aw5" card="one" alloy="Cancel">
			<label>.*</label>
		</action_widget>
		<input_widget id="iw2" card="some" alloy="Input">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="confirmation" card="lone" alloy="Confirm">
		<title>.*</title>
		<modal>true</modal>
		<root>any</root>
		<action_widget id="aw6" card="one" alloy="Ok">
			<label>.*</label>
		</action_widget>
		<action_widget id="aw7" card="one" alloy="Cancel">
			<label>.*</label>
		</action_widget>
		<input_widget id="iw2" card="none" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<edge>
		<from>aw1</from>
		<to>form_1</to>
	</edge>
	<edge>
		<from>aw3</from>
		<to>initial</to>
	</edge>
	<edge>
		<from>aw2</from>
		<to>form_2</to>
		<to>confirmation</to>
	</edge>
	<edge>
		<from>aw4</from>
		<to>form_2</to>
		<to>confirmation</to>
	</edge>
	<edge>
		<from>aw5</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
	<edge>
		<from>aw7</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
</pattern>

=== danydunk/Augusto/files/xml/crud.xml
<?xml version="1.0" encoding="UTF-8"?>
<pattern xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../xml_schemas/Pattern_schema.xsd"
	alloy="CRUD.als">
	<window id="initial" card="one" alloy="Initial">
		<title>.*</title>
		<modal>any</modal>
		<root>true</root>
		<action_widget id="paw1" card="some" alloy="Create_trigger">
			<label>.*(add|new|create).*</label>
		</action_widget>
		<action_widget id="paw2" card="some" alloy="Read_trigger">
			<label>.*(read|view).*</label>
		</action_widget>
		<action_widget id="paw3" card="some" alloy="Update_trigger">
			<label>.*(edit|update|modify).*</label>
		</action_widget>
		<action_widget id="paw4" card="some" alloy="Delete_trigger">
			<label>.*(delete|remove).*</label>
		</action_widget>
		<selectable_widget id="psw1" card="one" alloy="">
			<label>.*</label>
			<size>.*</size>
		</selectable_widget>
	</window>
	<window id="form_1" card="one" alloy="Form">
		<title>.*</title>
		<modal>any</modal>
		<root>false</root>
		<action_widget id="paw5" card="one" alloy="Ok">
			<label>.*(next|ok|save).*</label>
		</action_widget>
		<action_widget id="paw6" card="one" alloy="Cancel">
			<label>.*(back|cancel|back).*</label>
		</action_widget>
		<input_widget id="piw1" card="some" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="form_2" card="set" alloy="Form">
		<title>.*</title>
		<modal>any</modal>
		<root>false</root>
		<action_widget id="paw7" card="one" alloy="Ok">
			<label>.*(next|ok|save).*</label>
		</action_widget>
		<action_widget id="paw8" card="one" alloy="Cancel">
			<label>.*(back|cancel|back).*</label>
		</action_widget>
		<input_widget id="piw2" card="some" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="confirmation" card="lone" alloy="Confirm">
		<title>.*</title>
		<modal>true</modal>
		<root>false</root>
		<action_widget id="paw9" card="one" alloy="Ok">
			<label>.*(confirm|ok|yes).*</label>
		</action_widget>
		<action_widget id="paw10" card="one" alloy="Cancel">
			<label>.*(cancel|back|no).*</label>
		</action_widget>
		<input_widget id="piw2" card="none" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="confirmation_del" card="lone" alloy="Confirm_delete">
		<title>.*</title>
		<modal>true</modal>
		<root>false</root>
		<action_widget id="paw11" card="one" alloy="Ok">
			<label>.*(confirm|ok|yes).*</label>
		</action_widget>
		<action_widget id="paw12" card="one" alloy="Cancel">
			<label>.*(cancel|back|no).*</label>
		</action_widget>
		<input_widget id="piw3" card="none" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="view" card="one" alloy="View">
		<title>.*</title>
		<modal>any</modal>
		<root>false</root>
		<action_widget id="paw13" card="one" alloy="Ok">
			<label>.*(ok|back).*</label>
		</action_widget>
		<input_widget id="piw3" card="some" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<edge type="static">
		<from>paw1</from>
		<to>form_1</to>
	</edge>
	<edge type="static">
		<from>paw6</from>
		<to>initial</to>
	</edge>
	<edge type="static">
		<from>paw10</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
	<edge type="static">
		<from>paw12</from>
		<to>initial</to>
	</edge>
	<edge type="dynamic">
		<from>paw2</from>
		<to>view</to>		
	</edge>
	<edge type="dynamic">
		<from>paw3</from>
		<to>form_1</to>		
	</edge>
	<edge type="dynamic">
		<from>paw4</from>
		<to>confirmation_del</to>
		<to>initial</to>					
	</edge>
	<edge type="dynamic">
		<from>paw5</from>
		<to>form_2</to>
		<to>confirmation</to>
		<to>initial</to>		
	</edge>
	<edge type="dynamic">
		<from>paw7</from>
		<to>form_2</to>
		<to>confirmation</to>
		<to>initial</to>										
	</edge>
	<edge type="static">
		<from>paw8</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
	<edge type="dynamic">
		<from>paw9</from>
		<to>initial</to>
	</edge>
	<edge type="static">
		<from>paw10</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
	<edge type="dynamic">
		<from>paw11</from>
		<to>initial</to>
	</edge>
	<edge type="static">
		<from>paw13</from>
		<to>initial</to>		
	</edge>
</pattern>

=== danydunk/Augusto/files/xml/add_pattern_labelfree.xml
<?xml version="1.0" encoding="UTF-8"?>
<pattern xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../xml_schemas/Pattern_schema.xsd"
	alloy="ADD.als">
	<window id="initial" card="one" alloy="Initial">
		<title>.*</title>
		<modal>any</modal>
		<root>any</root>
		<action_widget id="paw1" card="one" alloy="Trigger">
			<label>.*</label>
		</action_widget>
		<selectable_widget id="psw1" card="one" alloy="List">
			<label>.*</label>
			<size>.*</size>
		</selectable_widget>
	</window>
	<window id="form_1" card="one" alloy="Form">
		<title>.*</title>
		<modal>any</modal>
		<root>any</root>
		<action_widget id="paw2" card="one" alloy="Ok">
			<label>.*</label>
		</action_widget>
		<action_widget id="paw3" card="one" alloy="Cancel">
			<label>.*</label>
		</action_widget>
		<input_widget id="piw1" card="some" alloy="Input">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="form_2" card="set" alloy="Form">
		<title>.*</title>
		<modal>any</modal>
		<root>any</root>
		<action_widget id="paw4" card="one" alloy="Ok">
			<label>.*</label>
		</action_widget>
		<action_widget id="paw5" card="one" alloy="Cancel">
			<label>.*</label>
		</action_widget>
		<input_widget id="piw2" card="some" alloy="Input">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<window id="confirmation" card="lone" alloy="Confirm">
		<title>.*</title>
		<modal>true</modal>
		<root>any</root>
		<action_widget id="paw6" card="one" alloy="Ok">
			<label>.*</label>
		</action_widget>
		<action_widget id="paw7" card="one" alloy="Cancel">
			<label>.*</label>
		</action_widget>
		<input_widget id="piw2" card="none" alloy="">
			<label>.*</label>
			<text>.*</text>
		</input_widget>
	</window>
	<edge type="static">
		<from>paw1</from>
		<to>form_1</to>
	</edge>
	<edge type="static">
		<from>paw3</from>
		<to>initial</to>
	</edge>
	<edge type="dynamic">
		<from>paw2</from>
		<to>form_2</to>
		<to>confirmation</to>
	</edge>
	<edge type="dynamic">
		<from>paw4</from>
		<to>form_2</to>
		<to>confirmation</to>
	</edge>
	<edge type="static">
		<from>paw5</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
	<edge type="static">
		<from>paw7</from>
		<to>form_2</to>
		<to>form_1</to>
	</edge>
</pattern>
